### ISSUE TITLE
1.0.6版本编辑器保存配置存在问题

### ISSUE THREAD

**Issue by mjfme** [No78Vino/gameplay-ability-system-for-unity#10]
环境版本：
unity 2022.3.23
odin 3.2.1
GAS 1.0.6

复现步骤:
下载当前项目zip包，复制GAS目录到空白unity，打开EX-GAS菜单--->点击检查子目录和基础配置按钮--->切换到Tags页面-->随意添加一个tag-->点击【生成taglib】
可以发现刚才添加的tag丢失了

**Comment by No78Vino** [comment]
感谢反馈，今明两天会尽快修复这个问题

**Comment by No78Vino** [comment]
1.0.7已更新，全局配置保存失败的问题已经修复。
