### ISSUE TITLE
编辑器弹窗：新增Tag，新增Attribute。光标移至边框后，出现异常没有变回白色箭头状态。

### ISSUE THREAD

**Issue by No78Vino** [No78Vino/gameplay-ability-system-for-unity#24]
![(M3YVKI_{X{T{NQ N0J9LGM](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/43328860/eed685af-ae0f-42b4-97e6-58811c4016f6)

编辑器弹窗：新增Tag，新增Attribute。光标移至边框后，出现异常没有变回白色箭头状态。

**Comment by GEFNENEN** [comment]
这是unity的bug, 把 window.ShowModel() 改成 别的非模式对话框就不会, 但是此场景应该使用模式对话框好一点
