### ISSUE TITLE
缓存Bug

### ISSUE THREAD

**Issue by GEFNENEN** [No78Vino/gameplay-ability-system-for-unity#26]
![16a13efd90730f0e8441e8678490825f](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/30926304/004967d4-ff44-4819-8fe2-b774f1e5d903)

进缓存池时, 会从MonoBehaviour的OnDisable辗转调用到AttributeAggregator.OnDispose()
从缓存池取出时, 没有再次调用将事件监听, 导致CurrentValue等不能正确刷新等

**Comment by No78Vino** [comment]
1.1.1版本已经修复这个bug。
