### ISSUE TITLE
更改配置路径后有问题

### ISSUE THREAD

**Issue by Penco81** [No78Vino/gameplay-ability-system-for-unity#28]
修改脚本生成路径和配置生成路径后，点击生成lib报错，重启unity后会解决

**Comment by No78Vino** [comment]
测试了新工程的路径配置流程，并未出现生成lib报错。能给出完整的过程复现吗？

**Comment by Penco81** [comment]
可以不用管了(Dog)应该是odin没有升级到3.2版本的原因....
