### ISSUE TITLE
2022.3 有编译错误

### ISSUE THREAD

**Issue by TaoJiaHengOne** [No78Vino/gameplay-ability-system-for-unity#30]
2022.3 
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/8c29785c-0aa8-46ac-a30e-72713397f774)
这行代码需要改下 不然编译不通过

**Comment by No78Vino** [comment]
Windows平台的编译没有遇到该问题。请问编译的平台是什么？EX-GAS的版本是多少（Setting的最上面会显示Version）？具体的编译错误能否截图？

**Comment by TaoJiaHengOne** [comment]
是 2021 版本 不是 2022 搞错了 
2022是正常的
