### ISSUE TITLE
技能等级 如何实现

### ISSUE THREAD

**Issue by TaoJiaHengOne** [No78Vino/gameplay-ability-system-for-unity#36]
假如实现一个 技能 比如狗头Q
一共4级 
伤害公式 
一级 100基础伤害 + 120% 攻击力 + (3 * 击杀层数)
二级 130基础伤害 + 120% 攻击力 + (3 * 击杀层数)
三级 170基础伤害 + 120% 攻击力 + (3 * 击杀层数)
四级 250基础伤害 + 120% 攻击力 + (3 * 击杀层数)

这里 4级伤害公式 创建4个同类型的MMD 和 4个 GE， 还是 在 Ability 里面自定义面板 配置技能数值
如果是Ability 配置 MMD 似乎拿不到 Ability

**Comment by No78Vino** [comment]
GameplayEffect是数据类，它本身是不带level的。GameplayEffectSpec是运行时执行类，他是有Level变量的，用来处理等级相关的自定义逻辑。

另外，其实不需要4个GE，一个GE就够了，4个公式可以合成到一个MMC中，MMC内部判断level做switch处理。

**Comment by TaoJiaHengOne** [comment]
GameplayEffectSpec 中的Level 似乎是 ASC的Level  而不是 Ability 的Level， 且无法在 Apply 前操作 GameplayEffectSpec
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/bf5d13c8-0805-4edd-be6c-424a2a052b92)

**Comment by TaoJiaHengOne** [comment]
无法在 Apply 之前操作Spec 设置 Level
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/efc7a5ff-4ac9-4364-be11-5363fc5abfc6)

**Comment by No78Vino** [comment]
instant ge的实例过程被封装了，原先是暴露在外面的。这确实是个问题。
因为apply ge的规范更新过了，所以把ge的实例过程封闭起来，导致现在instant策略的ge没办法修改其运行时的变量。

我会尽快更新补丁，加一个带level形参的apply ge重载函数。

spec的实例过程还是要封闭，因为tag的校验过程是包含了实例前到实例后，设计上是不允许这段逻辑里ge spec的变量（主要是tag部分）有变动。

**Comment by No78Vino** [comment]
EX-GAS 1.0 已更新至1.1.3，AbilitySystemComponent已追加：
1.ApplyGameplayEffectTo(GameplayEffect gameplayEffect, AbilitySystemComponent target,int effectLevel)
2.ApplyGameplayEffectToSelf(GameplayEffect gameplayEffect,int effectLevel)

时间轴能力的GE释放，暂时还没有传入等级的相关参数，默认依旧是ASC的等级。时间轴能力还在慢慢完善，后续会补充相关可选参数。

**Comment by TaoJiaHengOne** [comment]
感谢大佬

**Comment by No78Vino** [comment]
目前ge spec的apply问题还未完全解决，level只是因为是预留的变量。根本问题是用户对ge spec的修改应当允许在ge spec生效之前进行。 1.1.4会更新ge spec的实例化和生效流程。

**Comment by No78Vino** [comment]
1.1.4版本已更新。 ASC的ApplyGameplayEffectTo的Tag判断已经改为以GESpec为准，ASC新增了直接传入GESpec的Apply函数。现在可以在GESpec生效之前，对GESpec的参数进行修改操作。如果需要自定义指定GE的一些参数，可以通过SetByCaller MMC。具体可以参考文档的SetByCaller MMC的部分。

**Comment by TaoJiaHengOne** [comment]
感谢大佬
