### ISSUE TITLE
如何移除某个标签下所有的标签

### ISSUE THREAD

**Issue by TaoJiaHengOne** [No78Vino/gameplay-ability-system-for-unity#40]
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/d1081f96-146a-49f9-ae06-6cd3a00a8f0a)

如图 如何移除 State 下所有的TAG

**Comment by No78Vino** [comment]
按住shift多选，然后点右上角的删除tag。

**Comment by TaoJiaHengOne** [comment]
我的意思是运行时 
代码 如何 删除 一个目标 State 下所有的TAG

**Comment by No78Vino** [comment]
- 如果你是说体系内删除tags，没有明确的删除tag的概念，只有持有。因为gas体系内asc除了一开始初始化的固有tag，其余获得tag的渠道只有是gameplay effect和gameplay ability，而这两者授予的tag都是和他们的生命周期挂钩的。他们脱离了asc，asc自然就失去这些tag

- 如果你是说体系外用户手动删除tags，用这个：
```c#
    GameplayTagSet tags；// tag set的来源可以自定义，或者去GTagLib里遍历取需要的。
    ASC.RemoveFixedTags(stateTags)；
```

**Comment by TaoJiaHengOne** [comment]
好的
