### ISSUE TITLE
 CreateSpec  带 Granted Ability 会出现报错

### ISSUE THREAD

**Issue by TaoJiaHengOne** [No78Vino/gameplay-ability-system-for-unity#44]
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/346c80d7-d523-4809-89d6-79d194867f89)

似乎原因是在 GameplayEffectSpec 构造函数内 使用了  owner 变量
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/bcc11dc7-0d07-490f-aa77-bdd8a0c6a8d2)
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/4befb784-ab67-4dd3-97c6-c06bfca2b6fc)
![image](https://github.com/No78Vino/gameplay-ability-system-for-unity/assets/34653889/15537f1e-77fb-484e-8b69-09a13d0d00fd)

**Comment by No78Vino** [comment]
抱歉这是1.1.4优化GE实例化时，遗漏了Granted ability创建逻辑位置修改导致的。
1.1.6已经修复了该问题。
