### ISSUE TITLE
瞬时CUE 如何拿到 MMC的计算结果

### ISSUE THREAD

**Issue by TaoJiaHengOne** [No78Vino/gameplay-ability-system-for-unity#46]
做一个伤害飘字 如何在cue 中拿到 GE 中 MMC 的计算结果， 目前 CUE 的 Trigger 似乎实在 MMC 之前触发的

**Comment by No78Vino** [comment]
对，execution cue是在ge的modifier生效前执行的。
设计上，cue本身可以拿到来源ge的实例，而ge的运行时modifiers是public可以外部访问。cue完全可以提前算出伤害结果。
cue spec当中有cue parameter，cue parameter里包含来源：可以是ability，也可以是ge。


```
public abstract class GameplayCueSpec
    {
        protected readonly GameplayCue _cue;
        protected readonly GameplayCueParameters _parameters;
        public AbilitySystemComponent Owner { get; protected set; }

        public virtual bool Triggerable()
        {
            return _cue.Triggerable(Owner);
        }
        
        public GameplayCueSpec(GameplayCue cue, GameplayCueParameters cueParameters)
        {
            _cue = cue;
            _parameters = cueParameters;
            if (_parameters.sourceGameplayEffectSpec != null)
            {
                Owner = _parameters.sourceGameplayEffectSpec.Owner;
            }
            else if (_parameters.sourceAbilitySpec != null)
            {
                Owner = _parameters.sourceAbilitySpec.Owner;
            }
        }
    }
```


我之前的伤害飘字做法不是放在ge里，而是在血量attribute的变化监听里做的cue触发。
好处是不需要在每个带有伤害的ge里加上伤害飘字的cue；
坏处是无法知晓伤害来源，只能区分是受伤还是回血，也无法判断是否是暴击伤害等等。

**Comment by TaoJiaHengOne** [comment]
能否让CUE 在GE 执行完成后 在执行一个CUE 方法呢， 因为 伤害计算有暴击和命中，这些都是随机效果， 如果固定随机种子 又很麻烦.
如果可以在GE 伤害计算完毕后 执行一个CUE 方法， 可以通过读取 GE 的 Register 参数 进行各种自定义。
不过如果需要进行AI对伤害预测 执行一个最优的操作， 是否只能通过固定随机种子

**Comment by No78Vino** [comment]
那还是直接把execution cue执行挪到ge modifier生效之后吧，execution cue再区分生效前和生效后两类太没必要了。

1.1.7 追加的修改已经把execution cue执行挪到ge modifier生效之后了。
