### ISSUE TITLE
develop branch release

### ISSUE THREAD

**Issue by sablecanyon** [No78Vino/gameplay-ability-system-for-unity#50]
Hi,

Thanks for the useful repo! I noticed there are memory allocation issues in snapshotting stats and creating GameplayEffectSpecs. I saw that these issues have been fixed in the develop branch. When will these updates be released to Ex-Gas-1.0?

Thank you!

**Comment by sablecanyon** [comment]
I migrated to the develop branch and it went smoother than I expected. The memory issues have been fixed. Thanks again for this amazing repo!

**Comment by No78Vino** [comment]
Hey,buddy.  Actually, now I'm just developing a new version with ECS.  SO I think it's unnecessary to solve the GC problems for default branch. You can use the 'develop'  to replace  'ex-gas-1.0'. 

AND I'm really happy that you 're using this repo. I'll try my best to finish the ex-gas-2.0 (ECS version) before the end of the year.(*^_^*)
